package com.github.sigrarr.lunisolarcalc.spacebytime;

public enum Subject {
    ABERRATION_EARTH_SUN,
    EARTH_LATITUDE,
    EARTH_LONGITUDE,
    EARTH_NUTUATION_ELEMENTS,
    EARTH_NUTUATION_IN_LONGITUDE,
    EARTH_SUN_RADIUS,
    MOON_APPARENT_LONGITUDE,
    MOON_COORDINATE_ELEMENTS,
    MOON_EARTH_DISTANCE,
    MOON_LATITUDE,
    MOON_LONGITUDE,
    MOON_OVER_SUN_APPARENT_LONGITUDE_EXCESS,
    SUN_ABERRATED_LONGITUDE,
    SUN_APPARENT_LONGITUDE,
    SUN_GEOMETRIC_LONGITUDE,
    SUN_LATITUDE,
}
